<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="KALYAN" ignored="0" name="adding" tests="7" failures="2" timestamp="30 Aug 2020 16:01:26 GMT" time="4.986" errors="0">
  <testcase name="TestListen_1a" time="0.16" classname="com.Test_ng.parametertest"/>
  <testcase name="TestListen_2b" time="0.005" classname="com.Test_ng.parametertest"/>
  <testcase name="TestListen_3c" time="0.017" classname="com.Test_ng.parametertest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.Test_ng.parametertest.TestListen_3c(parametertest.java:53)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- TestListen_3c -->
  <testcase name="TestListen_testcaseConditionalSkipExecution_5e" time="0.608" classname="com.Test_ng.parametertest">
    <skipped/>
  </testcase> <!-- TestListen_testcaseConditionalSkipExecution_5e -->
  <testcase name="TestListen_testcaseSkipException_4d" time="0.008" classname="com.Test_ng.parametertest">
    <skipped/>
  </testcase> <!-- TestListen_testcaseSkipException_4d -->
  <testcase name="TestListen_timeoutTest_6f" time="1.023" classname="com.Test_ng.parametertest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.Test_ng.parametertest.TestListen_timeoutTest_6f() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.Test_ng.parametertest.TestListen_timeoutTest_6f() didn't finish within the time-out 1000
]]>
    </failure>
  </testcase> <!-- TestListen_timeoutTest_6f -->
  <testcase name="f" time="0.011" classname="com.Test_ng.parametertest"/>
</testsuite> <!-- adding -->
